//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.10 at 08:01:30 AM EST 
//


package net.joshuahughes.cookcontrol.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cooktype complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cooktype">
 *   &lt;complexContent>
 *     &lt;extension base="{}type">
 *       &lt;sequence>
 *         &lt;element name="thermometer" type="{}thermometertype" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cooktype", propOrder = {
    "thermometer"
})
public class Cooktype
    extends Type
{

    protected List<Thermometertype> thermometer;

    /**
     * Gets the value of the thermometer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the thermometer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getThermometer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Thermometertype }
     * 
     * 
     */
    public List<Thermometertype> getThermometer() {
        if (thermometer == null) {
            thermometer = new ArrayList<Thermometertype>();
        }
        return this.thermometer;
    }

}
