//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.09 at 07:19:47 PM EST 
//


package net.joshuahughes.smokercontroller.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the net.joshuahughes.smokercontroller.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Smokercontroller_QNAME = new QName("", "smokercontroller");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: net.joshuahughes.smokercontroller.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createType() {
        return new Type();
    }

    /**
     * Create an instance of {@link Smokercontrollertype }
     * 
     */
    public Smokercontrollertype createSmokercontrollertype() {
        return new Smokercontrollertype();
    }

    /**
     * Create an instance of {@link Alerttype }
     * 
     */
    public Alerttype createAlerttype() {
        return new Alerttype();
    }

    /**
     * Create an instance of {@link Smoketype }
     * 
     */
    public Smoketype createSmoketype() {
        return new Smoketype();
    }

    /**
     * Create an instance of {@link Platformtype }
     * 
     */
    public Platformtype createPlatformtype() {
        return new Platformtype();
    }

    /**
     * Create an instance of {@link Thermometertype }
     * 
     */
    public Thermometertype createThermometertype() {
        return new Thermometertype();
    }

    /**
     * Create an instance of {@link Type.Comment }
     * 
     */
    public Type.Comment createTypeComment() {
        return new Type.Comment();
    }

    /**
     * Create an instance of {@link Type.Property }
     * 
     */
    public Type.Property createTypeProperty() {
        return new Type.Property();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Smokercontrollertype }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "smokercontroller")
    public JAXBElement<Smokercontrollertype> createSmokercontroller(Smokercontrollertype value) {
        return new JAXBElement<Smokercontrollertype>(_Smokercontroller_QNAME, Smokercontrollertype.class, null, value);
    }

}
